PunktDe:
  Form:
    Persistence:
      finisher:
        excludedFormTypes:
          'Neos.Form:StaticText': true

      exportDefinitions:
        csv:
          label: Generic CSV
          exporter: csv
          fileNamePattern: "Form-Export-{formIdentifier}-{currentDate}.csv"

        excel:
          label: Generic Xlsx
          exporter: xlsx
          fileNamePattern: "Form-Export-{formIdentifier}-{currentDate}.xlsx"



      exporter:
        csv:
          className: PunktDe\Form\Persistence\Domain\Exporter\CsvExporter
          options: [ ]
        xlsx:
          className: PunktDe\Form\Persistence\Domain\Exporter\SpreadSheetExporter
          options:
            writerType: 'Xlsx'
            title: ''
            creator: ''


      processorChain:
        # Flatten nested fields into an array with namespaces
        flattenArray:
          class: 'PunktDe\Form\Persistence\Domain\Processors\FlattenArrayProcessor'
          position: 'start'

        # Map data keys from form defined keys to output keys. Drop unmapped fields.
        fieldKeyMapping:
          class: 'PunktDe\Form\Persistence\Domain\Processors\FieldKeyMappingProcessor'

        # Convert form values to an exportable representation. Eg. Uploaded data to its filename
        valueFormatting:
          class: 'PunktDe\Form\Persistence\Domain\Processors\ValueFormattingProcessor'

      scheduledExport:
        senderName: Scheduled Form Data Export
        senderMailAddress: noreply@localhost
        subject: "Latest data of form {formIdentifier}"

      formDataCleanup:
        retentionPeriod: 'P30D'
